mp.jwt.verify.issuer=produtos-api

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

mp.messaging.outgoing.estoque-out.connector=smallrye-kafka
mp.messaging.outgoing.estoque-out.topic=estoque-baixo

mp.messaging.incoming.estoque-in.connector=smallrye-kafka
mp.messaging.incoming.estoque-in.topic=estoque-baixo

# libera auth
quarkus.http.auth.permission.auth.paths=/auth/*
quarkus.http.auth.permission.auth.policy=permit

# TEMPORARIAMENTE COMENTAR
# quarkus.http.auth.permission.api.paths=/*
# quarkus.http.auth.permission.api.policy=authenticated
# Banco H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:produtos
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create

# Console do H2
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2

# Mostrar SQL
quarkus.hibernate-orm.log.sql=true